title: Graph Neural Networks - From Zero to Hero
description: International Conference on Advanced Research in Computing (ICARC-2025)- Tutorials
# show_downloads: true
# google_analytics:
theme: jekyll-theme-cayman

github:
  zip_url: https://github.com/BrAINLabs-Inc/ICARC_2025_GNN_Tutorial/archive/refs/heads/main.zip
  tar_url: https://github.com/BrAINLabs-Inc/ICARC_2025_GNN_Tutorial/archive/refs/heads/main.tar.gz
show_downloads: true  # This enables the download buttons

