title: Graph Neural Networks - From Zero to Hero
description: International Conference on Advanced Research in Computing (ICARC-2025)- Tutorials
# show_downloads: true
# google_analytics:
theme: jekyll-theme-cayman

